#include <platform_include.h>      /* System and IOP register bit and address definitions. */

#include "ADDS_21479_EzKit.h"
#include "initSPORT01_I2S_mode.h"

/* SPORT RX DMA destination buffers */
section("seg_dmda") int RxBlock_A0[RX_BLOCK_SIZE];
section("seg_dmda") int RxBlock_A1[sizeof(RxBlock_A0)];

/* SPORT Tx DMA source buffers */
section("seg_dmda") int TxBlock_A0[TX_BLOCK_SIZE];
section("seg_dmda") int TxBlock_A1[sizeof(TxBlock_A0)];

/* SPORT RX DMA destination buffers */
section("seg_dmda") int RxBlock_B0[RX_BLOCK_SIZE];
section("seg_dmda") int RxBlock_B1[sizeof(RxBlock_B0)];

/* SPORT Tx DMA source buffers */
section("seg_dmda") int TxBlock_B0[TX_BLOCK_SIZE];
section("seg_dmda") int TxBlock_B1[sizeof(TxBlock_B0)];

/* Set up the TCBs to rotate automatically */
int TCB_RxBlock_A0[4] = { 0, sizeof(RxBlock_A0), 1, 0};
int TCB_RxBlock_A1[4] = { 0, sizeof(RxBlock_A0), 1, 0};

int TCB_TxBlock_A0[4] = { 0, sizeof(TxBlock_A0), 1, 0};
int TCB_TxBlock_A1[4] = { 0, sizeof(TxBlock_A0), 1, 0};

int TCB_RxBlock_B0[4] = { 0, sizeof(RxBlock_B0), 1, 0};
int TCB_RxBlock_B1[4] = { 0, sizeof(RxBlock_B0), 1, 0};

int TCB_TxBlock_B0[4] = { 0, sizeof(TxBlock_B0), 1, 0};
int TCB_TxBlock_B1[4] = { 0, sizeof(TxBlock_B0), 1, 0};

void initSPORT()
{

	/* Set up "ping-pong" chained DMAs for CS4272 */

	/* Proceed from Block A0 to Block A1 */
	/* Extract 19-bits of the receive buffer A1 address with setting PCI bit */
    TCB_RxBlock_A0[0] = (unsigned int) TCB_RxBlock_A1 + 3 - OFFSET + PCI ;
    TCB_RxBlock_A0[3] = (int) RxBlock_A0 - OFFSET ;

    /* Proceed from Block A0 to Block A1*/
    /* Extract 19-bits of the transmit buffer A1 address */
    TCB_TxBlock_A0[0] = (unsigned int) TCB_TxBlock_A1 + 3 - OFFSET ;
    TCB_TxBlock_A0[3] = (int) TxBlock_A0 - OFFSET ;

    /* Proceed from Block A1 to Block A0 */
    /* Extract 19-bits of the receive buffer A0 address with setting PCI bit */
    TCB_RxBlock_A1[0] = (unsigned int) TCB_RxBlock_A0 + 3 - OFFSET + PCI ;
    TCB_RxBlock_A1[3] = (int) RxBlock_A1 - OFFSET ;

    /* Proceed from Block A1 to Block A0 */
    /* Extract 19-bits of the transmit buffer A0 address */
    TCB_TxBlock_A1[0] = (unsigned int) TCB_TxBlock_A0 + 3 - OFFSET ;
    TCB_TxBlock_A1[3] = (int) TxBlock_A1 - OFFSET ;
    
    /* Proceed from Block B0 to Block B1 */
    /* Extract 19-bits of the receive buffer B1 address with setting PCI bit */
    TCB_RxBlock_B0[0] = (unsigned int) TCB_RxBlock_B1 + 3 - OFFSET + PCI ;
    TCB_RxBlock_B0[3] = (int) RxBlock_B0 - OFFSET ;

    /* Proceed from Block B0 to Block B1 */
    /* Extract 19-bits of the transmit buffer B1 address */
    TCB_TxBlock_B0[0] = (unsigned int) TCB_TxBlock_B1 + 3 - OFFSET ;
    TCB_TxBlock_B0[3] = (int) TxBlock_B0 - OFFSET ;

    /* Proceed from Block B1 to Block B0 */
    /* Extract 19-bits of the receive buffer B0 address with setting PCI bit */
    TCB_RxBlock_B1[0] = (unsigned int) TCB_RxBlock_B0 + 3 - OFFSET + PCI ;
    TCB_RxBlock_B1[3] = (int) RxBlock_B1 - OFFSET ;

    /* Proceed from Block B1 to Block B0 */
    /* Extract 19-bits of the transmit buffer B0 address */
    TCB_TxBlock_B1[0] = (unsigned int) TCB_TxBlock_B0 + 3 - OFFSET ;
    TCB_TxBlock_B1[3] = (int) TxBlock_B1 - OFFSET ;
    
	/* Clear out SPORT 0/1 registers */
    *pSPCTL0  = *pSPCTL1  = 0;
    *pSPMCTL0 = *pSPMCTL1 = 0;
    *pSPCTLN1 = *pSPCTLN0 = 0;

    /* External clock and frame syncs generated by CS4272 */
   	*pDIV0 = 0x00000000;  /* transmitter(SPORT0) */
    *pDIV1 = 0x00000000;  /* receiver(SPORT1) */
    
    /* Enabling DMA Chaining for SPORT0 TX/SPORT1 RX */
    /* Block 1 will be filled first */
    /* Initialize the chain pointer for the transmitter with PCI bit set to enable the interrupts after every TCB */
    *pCPSP0A = (unsigned int)TCB_TxBlock_A0 - OFFSET + 3 + PCI;
    *pCPSP0B = (unsigned int)TCB_TxBlock_B0 - OFFSET + 3 + PCI;
    *pCPSP1A = (unsigned int)TCB_RxBlock_A0 - OFFSET + 3;
    *pCPSP1B = (unsigned int)TCB_RxBlock_B0 - OFFSET + 3;
   
	/* SPORT1 control register is set up as a receiver in I2S for ADC1 and ADC2 */
	/* SPORT1  control register SPCTL1 = 0x00000000 */
	/* externally generated SCLK1 and RFS1 */
	/* primary and secondary channels enabled with DMA chaining */
	*pSPCTL1 = OPMODE | SPEN_A | SCHEN_A | SDEN_A | SLEN32 | SPEN_B | SCHEN_B | SDEN_B;
	
	/* SPORT0 control register set up as a transmitter in I2S for DAC1 and DAC2*/
	/* externally generated SCLK0 and RFS0 */
	/* primary and secondary channels enabled with DMA chaining */
	*pSPCTL0 = OPMODE | SPEN_A | SCHEN_A | SDEN_A | SLEN32 | SPEN_B | SCHEN_B | SDEN_B | SPTRAN;
}


